export const LOAD_LIBRARY="LOAD_LIBRARY"
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_FAIL = 'CREATE_LIBRARY_FAIL';
export const DELETE_LIBRARY = 'DELETE_LIBRARY';
export const GET_ALL_LIBRARY = 'GET_ALL_LIBRARY';
export const GET_ALL_LIBRARY_FAIL = 'GET_ALL_LIBRARY_FAIL ';
export const GET_VIDEO = 'GET_VIDEO';
export const GET_VIDEO_FAIL = 'GET_VIDEO_FAIL ';